spring:
  profiles:
    active: dev_why
  devtools:
    restart:
      enabled: true  # Enable hot deployment
      additional-paths: src/main/java # Restart directory
      exclude: WEB-INF/**
  freemarker:
    cache: false  # Disable cache to allow immediate effect when modifying pages
  mvc:
    static-path-pattern: /**
  #    path match:
  #      matching-strategy: ANT_PATH_MATCHER

  servlet:
    multipart:
      max-file-size: 10MB # Maximum file size for HTTP uploads
      max-request-size: 10MB # Maximum total size for HTTP uploads at once

  web:
    resources:
      static-locations: /upload/

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: org.postgresql.Driver

  main:
    allow-circular-references: true