server:
  port: 8080

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/java2_project
#    username: postgres
#    password: 111111

#    url: jdbc:postgresql://localhost:5432/java2_project
#    username: postgres
#    password: rin186210

#    url: jdbc:postgresql://114.132.51.227:5432/java2_project
#    username: admin_java2_project
#    password: '@4Em~hD9EoPkEVEL3tgWY@'