server:
  port: 8085
  ssl:
#    enabled: true
#    key-store: ../keystore_football.p12
#    key-store-type: PKCS12
#    key-store-password: 111111
#    key-alias: ssl_football

    enabled: true
    key-store: ../haoyu-wang141.top.pfx
    key-store-type: PKCS12
    key-store-password: 5bm5uflq5p7d
    key-alias: haoyu-wang141.top

spring:
  datasource:
    url: jdbc:postgresql://114.132.51.227:5432/football
    username: admin_football
    password: 111111

file:
  upload-dir: /home/lighthouse/SUSTech-Football-Upload/